/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_fr_lirmm_fca4j_core_natif_NativeBridge
#define _Included_fr_lirmm_fca4j_core_natif_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif

/* Pipeline DBasis complet (mode MONO) */
JNIEXPORT jstring JNICALL
Java_fr_lirmm_fca4j_core_natif_NativeBridge_runDbasis(
    JNIEnv *, jclass, jint, jint, jbyteArray, jobjectArray, jint, jint);

/* computeMinimalGenerators (mode MULTITHREAD) */
JNIEXPORT jobjectArray JNICALL
Java_fr_lirmm_fca4j_core_natif_NativeBridge_computeMinimalGenerators(
    JNIEnv *, jclass, jint, jint, jbyteArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
